version: '3'

services:
  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - '6379'

  db:
    image: postgres:14.7-alpine
    restart: on-failure
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', '-c', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 10s
      retries: 5
      timeout: 5s

  habits:
    build: .
    tty: true
    ports:
      - '8000:8000'
    command:
      sh -c 'python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/habits
    env_file:
      - .env

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/habits
    depends_on:
      - redis
      - db
      - habits

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/habits
    depends_on:
      - redis
      - db
      - habits
      - celery

volumes:
  postgres_data:
